apiVersion: v1
kind: Service
metadata:
  name: mcp-raider
  labels:
    app: mcp-raider
spec:
  type: ClusterIP
  ports:
    - port: 3001
      targetPort: 3001
      protocol: TCP
      name: http
  selector:
    app: mcp-raider
